### ISSUE TITLE
系统运行环境需求

### ISSUE THREAD

**Issue by tony80437** [xiangechen/chili3d#15]
请问需要npm和node的什么版本运行？目前在ubuntu 20.04下，安装了npm 6.14.4和node 10.19.0，都是系统命令apt安装的，运行这个系统有错误.

root@chili3d-dev:/opt/data/chili3d# npm run dev

> chili3d@0.1.0 dev /opt/data/chili3d
> npx rspack dev

yargs parser supports a minimum Node.js version of 12. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chili3d@0.1.0 dev: `npx rspack dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chili3d@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-04-29T05_23_15_221Z-debug.log

**Comment by xiangechen** [comment]
推荐node版本为20及以上

**Comment by tony80437** [comment]
换成20版本，前面的问题都可以了，运行时说这个模块找不到，是不是依赖项没定义？
root@chili3d-dev:/opt/data/chili3d# npm run dev

> chili3d@0.1.0 dev
> npx rspack dev

node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module '@rspack/core'
Require stack:
- /opt/data/chili3d/node_modules/@rspack/dev-server/dist/server.js

手动安装  npm i @repack/core 后运行后出现很多这个错误:

ERROR in ./packages/chili-builder/src/additionalModule.ts
  × Module parse failed:
  ╰─▶   × JavaScript parsing error: Expected '{', got 'interface'
         ╭─[3:1]
       3 │ import { CommandKeys, I18nKeys, Locale } from "chili-core";
       4 │
       5 │ export interface AdditionalCommand {
         ·        ─────────
       6 │     tabName: I18nKeys;
       7 │     groupName: I18nKeys;
         ╰────
      
  help: 
        You may need an appropriate loader to handle this file type.

**Comment by xiangechen** [comment]
你更新了rspack的版本吧？rspack/core的依赖应该是rspack0.5版引入的破坏性更新，等rspack1.0版发布后再统一更新吧。
解决方法：还原所有的依赖版本，再执行npm i，然后运行npm run dev应该就没问题了。

**Comment by tony80437** [comment]
当时应该是执行了一个提示的什么修复命令，把依赖项改掉了。按你说的重新来一遍，现在没问题了。
