### ISSUE TITLE
导入stp模型只能作为一个整体

### ISSUE THREAD

**Issue by TRYOKETHEPEN** [xiangechen/chili3d#19]
你好，感谢你这个项目。
我按照指南启动项目后，访问web页面。
导入stp文件后，左侧项目树中，导入的模型只显示为一个整体，右侧编辑页面中也没法选中模型的零件。
再导出为stp文件后，通过FreeCAD软件打开，是有保留零件信息的。

之前对three.js有所了解，.stp需要转换为.glb后再通过three.js加载，在转换过程中，模型内部的零件信息会丢失，变为一个整体。

请问目前在web编辑器里，导入的stp模型只能作为一个整体吗？
有没有计划实现这样的功能：
导入stp后，按照其结构树将各部分零件分别转换为glb，再通过three.js加载其所有零件，形成与原始stp结构树相同的装配关系。

**Comment by xiangechen** [comment]
step格式的导入后续会升级，会解决颜色及整体导入的问题

**Comment by TRYOKETHEPEN** [comment]
> step格式的导入后续会升级，会解决颜色及整体导入的问题

感谢回复，期待项目更新
