### ISSUE TITLE
sig导出会乱的问题

### ISSUE THREAD

**Issue by Mywbj** [xiangechen/chili3d#20]
例如我画了一个立方体，导出IGS 然后再导入会乱或者丢失，如图：
![QQ_1722939521672](https://github.com/user-attachments/assets/b5ca401e-9420-49f3-a65c-7d5977d61f04)

然后这个是STP的导出，然后导入是正常的，如图：
![QQ_1722939573466](https://github.com/user-attachments/assets/e180561c-153a-466f-8147-6f5452a6db7b)

是什么问题呢，希望大佬帮忙解决一下

**Comment by xiangechen** [comment]
occ 导入那里出问题了，occ 模块会重写，要去掉 opencascade.js

**Comment by Mywbj** [comment]
> occ 导入那里出问题了，occ 模块会重写，要去掉 opencascade.js

大佬 这个大概什么时候可以修复呢，着急用

**Comment by xiangechen** [comment]
现在0.3版再测试一周就发布了，0.4版本会添加各种数据格式交换的模块，具体时间一到两个月吧。你如果急的话，暂时用step格式吧。

**Comment by Mywbj** [comment]
> 现在0.3版再测试一周就发布了，0.4版本会添加各种数据格式交换的模块，具体时间一到两个月吧。你如果急的话，暂时用step格式吧。

大佬occ 模型转换igs格式文件是你写的库吗？具体怎么实现的，能不能学习一下

**Comment by Mywbj** [comment]
大佬　这个ｂｕｇ能修复吗？我看FreeCAD也是这种情况

**Comment by xiangechen** [comment]
已修复
