### ISSUE TITLE
igs原文件18m，导出stp56m

### ISSUE THREAD

**Issue by Mywbj** [xiangechen/chili3d#21]
igs原文件18m（总共有5100多个模型组成），导出stp56m，18m的文件 然后导出stp要1个多小时，这个还能优化吗？
![QQ_1723001975551](https://github.com/user-attachments/assets/2eecf731-35e2-4d3a-87d7-d22ce1abe4c2)

![QQ_1723001944986](https://github.com/user-attachments/assets/fb7ef63f-d7f0-420c-8bff-049a7b3d9e83)

**Comment by xiangechen** [comment]
igs已可导出
