### ISSUE TITLE
导入ｉｇｅ文件爆栈了

### ISSUE THREAD

**Issue by Mywbj** [xiangechen/chili3d#23]
![6b0ddb054e7b1be86f9eca3885360f4](https://github.com/user-attachments/assets/3777c83e-2522-4cff-acbe-bc473d0fa5ce)
导入ｉｇｅ文件爆栈了
有1688个组成
![QQ_1726304408646](https://github.com/user-attachments/assets/42d79eb3-b96a-4fe4-85ee-3afbe8accd84)

**Comment by xiangechen** [comment]
最近在进行文件导入导出的相关开发，方便的话可以将文件发我邮箱：xiangetg@msn.cn，谢谢

**Comment by Mywbj** [comment]
> 最近在进行文件导入导出的相关开发，方便的话可以将文件发我邮箱：[xiangetg@msn.cn](mailto:xiangetg@msn.cn)，谢谢

已经发过去了，还有个问题就是，导入的时候建议可以分段导入，就不会卡死一段时间了，例如利用requestIdleCallback　浏览器空闲的时候
