### ISSUE TITLE
材质贴图问题

### ISSUE THREAD

**Issue by Mywbj** [xiangechen/chili3d#28]
这个是自己画的可以正常贴图：
![QQ_1731033137316](https://github.com/user-attachments/assets/fec86df5-44a0-4a73-9988-6bf5fcc8e4b8)

下面这个是导出后 再导入 无法进行修改贴图了：
![QQ_1731033375396](https://github.com/user-attachments/assets/f675bb6f-a750-45fc-a987-a9b58b182601)

我看旧版本的导入一样可以支持贴图的哦

**Comment by xiangechen** [comment]
更新后引入的bug，已经修复了

**Comment by Mywbj** [comment]
![QQ_1731290029999](https://github.com/user-attachments/assets/acc1a475-8bcf-42b1-a06c-932b2c0e3205)
这个兼容了吗，在哪个版本可以解决

**Comment by xiangechen** [comment]
这个是文件版本有升级，即打开的文件是旧版本创建的，新版本无法打开。在程序到达 1.0 以前都不会考虑向下兼容问题。
