### ISSUE TITLE
chili-wasm编译失败

### ISSUE THREAD

**Issue by zhaosky** [xiangechen/chili3d#32]
我根据cpp目录的readme编译wasm，提示build找不到occt模块如下：
```cpp
CMake Error at CMakeLists.txt:29 (file):
  file STRINGS file
  "D:/code/Code/github/chili3d/cpp/build/occt/src/TKernel/PACKAGES" cannot be
  read.


CMake Error at CMakeLists.txt:29 (file):
  file STRINGS file
  "D:/code/Code/github/chili3d/cpp/build/occt/src/TKMath/PACKAGES" cannot be
  read.
```
这个occt的模块要怎么导入啊？

**Comment by xiangechen** [comment]
你看一下cpp/build/occt目录是否存在。执行npm run setup:wasm会在GitHub上拉取occ，但很有可能失败，要看到**Setup complete**才算成功。

**Comment by zhaosky** [comment]
> 你看一下cpp/build/occt目录是否存在。执行npm run setup:wasm会在GitHub上拉取occ，但很有可能失败，要看到**Setup complete**才算成功。

谢谢指点。
